apiVersion: v1
kind: PersistentVolume
metadata:
  name: ag-tmp-gateway-pv
  namespace: dynatrace

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-07bc816fcaca981e6