apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desafio-meli-app
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: desafio-meli-app
            port:
              number: {{ .Values.service.port }}